In [2]:
import pandas as pd
import plotly.express as px

In [3]:
df=pd.read_csv('restaurant_sales_data.csv')
df

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,Side Dishes,Side Salad,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,NaN,NaN,2.0,5.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash
...,...,...,...,...,...,...,...,...,...
17529,ORD_320102,CUST_021,Drinks,NaN,NaN,4.0,4.0,2023-12-23,Cash
17530,ORD_974128,CUST_069,Desserts,Ice Cream,5.0,3.0,15.0,2023-12-18,Cash
17531,ORD_108324,CUST_050,Desserts,Ice Cream,5.0,4.0,20.0,2022-05-20,Digital Wallet
17532,ORD_612647,CUST_073,Side Dishes,Mashed Potatoes,4.0,2.0,8.0,2022-01-27,Digital Wallet
17533,ORD_680707,CUST_006,Desserts,NaN,7.0,4.0,28.0,2023-01-07,NaN

In [3]:
df.groupby("Category")["Item"].nunique()

Category
Desserts       5
Drinks         5
Main Dishes    5
Side Dishes    5
Starters       6
Name: Item, dtype: int64

                                                                Data exploration

In [4]:
#1.Data info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        17534 non-null  str
 1   Customer ID     17534 non-null  str
 2   Category        17534 non-null  str
 3   Item            15776 non-null  str
 4   Price           16658 non-null  float64
 5   Quantity        17104 non-null  float64
 6   Order Total     17104 non-null  float64
 7   Order Date      17534 non-null  str
 8   Payment Method  16452 non-null  str
dtypes: float64(3), str(6)
memory usage: 2.1 MB

We can conclude that:
1.Order date is str we should convert it to date time "in cleaning stage"
2.there are diff in non null count "we can clear it from isna()

In [5]:
#2.null values
df.isna().sum()

Order ID             0
Customer ID          0
Category             0
Item              1758
Price              876
Quantity           430
Order Total        430
Order Date           0
Payment Method    1082
dtype: int64

In [6]:
#we need the presentage of nulls
df.isna().mean().round(2)*100
# We will handel this missing values in the "cleaning stage"

Order ID           0.0
Customer ID        0.0
Category           0.0
Item              10.0
Price              5.0
Quantity           2.0
Order Total        2.0
Order Date         0.0
Payment Method     6.0
dtype: float64

In [7]:
#3.Check duplicate
df.duplicated().sum()

np.int64(0)

In [8]:
#4.Check description of numerical data
df.describe().round(2)

          Price  Quantity  Order Total
count  16658.00  17104.00     17104.00
mean       6.59      3.01        19.91
std        4.83      1.41        18.73
min        1.00      1.00         1.00
25%        3.00      2.00         7.50
50%        5.00      3.00        15.00
75%        7.00      4.00        25.00
max       20.00      5.00       100.00

In [9]:
#5.Check description of categorical data
df.describe(include=object)

C:\Users\mohan\AppData\Local\Temp\ipykernel_1464\2292845361.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=object)

,Order ID,Customer ID,Category,Item,Order Date,Payment Method
count,17534,17534,17534,15776,17534,16452
unique,17534,100,5,26,730,3
top,ORD_705844,CUST_066,Main Dishes,Pasta Alfredo,2023-11-25,Credit Card
freq,1,207,3551,998,42,5504

------------------------  Cleaning Stage------------------

In [10]:
#1.We will start by the payment method col 
df['Payment Method'].nunique()

3

In [11]:
df['Payment Method'].unique()

<ArrowStringArray>
['Credit Card', 'Digital Wallet', 'Cash', nan]
Length: 4, dtype: str

In [12]:
df['Payment Method'].value_counts()

Payment Method
Credit Card       5504
Cash              5499
Digital Wallet    5449
Name: count, dtype: int64

In [13]:
#there are nan values so we need to know is it missing or what
df['Payment Method'].isnull().mean().round(2)*100 
#We will fill this 6% with unknown value till making a relation betwwen al nulls col. so if tere are any raw has nulls we will drop it

np.float64(6.0)

In [14]:
df['Payment Method']=df['Payment Method'].fillna('unknown')

In [42]:
df['Payment Method'].unique()
#now we have 4 payment methods

<ArrowStringArray>
['Credit Card', 'Digital Wallet', 'Cash', 'unknown']
Length: 4, dtype: str

In [44]:
#converting data type of col Order date from str to datetime
df['Order Date']=pd.to_datetime(df['Order Date'])

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        17534 non-null  str
 1   Customer ID     17534 non-null  str
 2   Category        17534 non-null  str
 3   Item            15776 non-null  str
 4   Price           16658 non-null  float64
 5   Quantity        17104 non-null  float64
 6   Order Total     17104 non-null  float64
 7   Order Date      17534 non-null  datetime64[us]
 8   Payment Method  17534 non-null  str
dtypes: datetime64[us](1), float64(3), str(5)
memory usage: 2.0 MB

In [46]:
df.head()
#now we destingutish that Order total is the result of multiplication of price with quantity 
#so we can  1.Rename Order Total to be Total price
           #2.calculating the missing values of any col.of these three col. from the athor two col.

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,Side Dishes,Side Salad,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,NaN,NaN,2.0,5.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

In [47]:
#1.Changing col.name
df.rename(columns={'Order Total':'Total price'},inplace=True)

In [48]:
df.head()

,Order ID,Customer ID,Category,Item,Price,Quantity,Total price,Order Date,Payment Method
0,ORD_705844,CUST_092,Side Dishes,Side Salad,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,NaN,NaN,2.0,5.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

In [50]:
df.isna().mean().round(2)*100
#We distigutish that  price missing value is 5% & quantity & total price 2% + price is result of division of total price divided by quantity

Order ID           0.0
Customer ID        0.0
Category           0.0
Item              10.0
Price              5.0
Quantity           2.0
Total price        2.0
Order Date         0.0
Payment Method     0.0
dtype: float64

In [51]:
#here we mask the price col. has null values when the Quantity & Total price have values
mask=(df['Price'].isna()&
df['Quantity'].notnull() &
df['Total price'].notnull())
df[mask]
# We will calculate the 446 rows of price col. from the another two col.

,Order ID,Customer ID,Category,Item,Price,Quantity,Total price,Order Date,Payment Method
3,ORD_630508,CUST_075,Drinks,NaN,NaN,2.0,5.0,2022-08-09,Credit Card
83,ORD_167858,CUST_056,Side Dishes,NaN,NaN,5.0,25.0,2022-04-01,Cash
112,ORD_289733,CUST_057,Drinks,NaN,NaN,5.0,5.0,2022-01-05,unknown
122,ORD_363522,CUST_070,Starters,NaN,NaN,1.0,8.0,2023-05-07,Credit Card
146,ORD_499199,CUST_079,Desserts,NaN,NaN,5.0,25.0,2022-02-12,Digital Wallet
...,...,...,...,...,...,...,...,...,...
17422,ORD_638163,CUST_080,Desserts,NaN,NaN,5.0,30.0,2022-06-11,Digital Wallet
17432,ORD_290007,CUST_088,Main Dishes,NaN,NaN,4.0,60.0,2022-06-22,Cash
17499,ORD_118085,CUST_089,Drinks,NaN,NaN,4.0,12.0,2023-04-09,Digital Wallet
17509,ORD_239707,CUST_056,Starters,NaN,NaN,1.0,8.0,2023-07-27,Credit Card
17529,ORD_320102,CUST_021,Drinks,NaN,NaN,4.0,4.0,2023-12-23,Cash

In [52]:
df.loc[mask,'Price']=(df.loc[mask,'Total price'] / df.loc[mask,'Quantity'])

In [53]:
df[mask].head(3)

,Order ID,Customer ID,Category,Item,Price,Quantity,Total price,Order Date,Payment Method
3,ORD_630508,CUST_075,Drinks,NaN,2.5,2.0,5.0,2022-08-09,Credit Card
83,ORD_167858,CUST_056,Side Dishes,NaN,5.0,5.0,25.0,2022-04-01,Cash
112,ORD_289733,CUST_057,Drinks,NaN,1.0,5.0,5.0,2022-01-05,unknown

In [54]:
df.isna().mean().round(2)*100
#now we found that % of missing value of price decreased to 2%

Order ID           0.0
Customer ID        0.0
Category           0.0
Item              10.0
Price              2.0
Quantity           2.0
Total price        2.0
Order Date         0.0
Payment Method     0.0
dtype: float64

In [ ]:
#Now We can make deep cleaning in the three col. which have 2% missing values 
# if the three col. have the missing values we can drop them 
mask2=(df['Price'].isnull()&
       df['Quantity'].isnull() &
       df['Total price'].isnull()
       &df['Item'].isnull())
df[mask2]
# So now it is clean that this 430 rows are missing values no data in col "item , price , quantity , total price & some of payment method are unknown "
# So we can drop this rows to clean our data as it acts only 2%

,Order ID,Customer ID,Category,Item,Price,Quantity,Total price,Order Date,Payment Method
75,ORD_367023,CUST_055,Side Dishes,NaN,NaN,NaN,NaN,2022-05-29,unknown
118,ORD_627458,CUST_058,Side Dishes,NaN,NaN,NaN,NaN,2023-08-24,Digital Wallet
131,ORD_467157,CUST_099,Drinks,NaN,NaN,NaN,NaN,2023-11-30,unknown
240,ORD_467033,CUST_032,Side Dishes,NaN,NaN,NaN,NaN,2023-03-04,Digital Wallet
253,ORD_722632,CUST_027,Desserts,NaN,NaN,NaN,NaN,2022-12-11,Credit Card
...,...,...,...,...,...,...,...,...,...
17410,ORD_882909,CUST_023,Drinks,NaN,NaN,NaN,NaN,2023-07-11,Credit Card
17451,ORD_529422,CUST_068,Drinks,NaN,NaN,NaN,NaN,2022-07-17,Credit Card
17473,ORD_342327,CUST_096,Desserts,NaN,NaN,NaN,NaN,2022-12-29,Cash
17497,ORD_205432,CUST_090,Drinks,NaN,NaN,NaN,NaN,2022-03-03,Cash
17506,ORD_563553,CUST_044,Main Dishes,NaN,NaN,NaN,NaN,2022-07-20,Digital Wallet

In [57]:
#Drop missing data in col item , price , quantity ,total price 
df.dropna(subset=['Item','Price','Quantity','Total price'],how='all',inplace=True)

In [ ]:
df.isna().mean().round(2)*100
#Now the item missing values decreased to 8 % & we can analys according to Category of items

Order ID          0.0
Customer ID       0.0
Category          0.0
Item              8.0
Price             0.0
Quantity          0.0
Total price       0.0
Order Date        0.0
Payment Method    0.0
dtype: float64

In [59]:
#some payment method were unknown & others are deleted with the nan values of the prevous col
# we need to know ho many known payment method
df['Payment Method'].value_counts(normalize=True)*100

Payment Method
Cash              31.641721
Credit Card       31.606642
Digital Wallet    31.238307
unknown            5.513330
Name: proportion, dtype: float64

In [60]:
df.head(3)

,Order ID,Customer ID,Category,Item,Price,Quantity,Total price,Order Date,Payment Method
0,ORD_705844,CUST_092,Side Dishes,Side Salad,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card

                                               Now we can starting analysis of The Data set

                                                    A.Customer column analysis

1.What are the top 10 customers orders?

In [61]:
cust_sale=df.groupby('Customer ID')['Order ID'].count().reset_index().sort_values(ascending=False,by='Order ID').head(10)
px.bar(cust_sale,x='Customer ID',y='Order ID',text_auto=True,title='Top Ten no.of orders')

2.Top customers payment

In [62]:
cust=df.groupby('Customer ID')['Total price'].sum().reset_index().sort_values(ascending=False,by='Total price').head(10)
px.histogram(cust,x='Customer ID',y='Total price',text_auto=True,title='Top Ten Payment')

3.least 5 orders

In [63]:
cust1=df.groupby('Customer ID')['Total price'].count().reset_index().sort_values(ascending=False,by='Total price').tail(5)
px.histogram(cust1,x='Customer ID',y='Total price',text_auto=True)

4.How many times each payment method used

In [64]:
paymeth=df.groupby('Payment Method')['Customer ID'].count().reset_index()
px.bar(paymeth,x='Payment Method',y='Customer ID',title='presentage of payment method',text_auto=True).update_xaxes(categoryorder='total descending')

5.How many customers in each month

In [67]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

cust_mon = (
    df.groupby(df['Order Date'].dt.to_period('M'))['Customer ID']
      .nunique()      # عدد العملاء المختلفين في كل شهر
      .reset_index()
)

cust_mon['Order Date'] = cust_mon['Order Date'].astype(str)

px.bar(cust_mon, x='Order Date', y='Customer ID',text_auto=True,title='Customers in each month')

6.How many Orderes of each items

In [68]:
ord_item=df.groupby('Item')['Customer ID'].count().reset_index()
px.bar(ord_item,x='Item',y='Customer ID',title='Amount of orders of items',text_auto=True,color_discrete_sequence=['green']).update_xaxes(categoryorder='total descending')

                                               B.Items analysis

7.Presentage of each Dish

In [69]:
px.pie(data_frame=df,names='Category',title='Presentage of each dish orders',width=850,hole=0.5)

---

8.Average item price

In [70]:
avg=df.groupby('Item')['Price'].mean().reset_index()
px.histogram(avg,x='Item',y='Price',title='Average cost of item',text_auto=True).update_xaxes(categoryorder='total descending')

9.Best selling Item

In [71]:
sell=df.groupby('Item')['Total price'].sum().reset_index()
px.histogram(sell,x='Item',y='Total price',title='Best item income',text_auto=True).update_xaxes(categoryorder='total descending')

10.Quantity of each item

In [72]:
#we made reset index avoid counting item as row so the index of rows starts from pasta alfredo
result=df.groupby('Item')['Quantity'].sum().reset_index().sort_values(ascending=False,by='Quantity')
px.bar(result,x='Item',y='Quantity',text_auto=True,title='Best selling Items',color_discrete_sequence=['yellow'])

                                                        C.Date time col

11.Sales of each year

In [73]:
sales_by_year = (df.groupby(df["Order Date"].dt.year)["Total price"].sum().reset_index())

px.bar(sales_by_year,x='Order Date',y='Total price',title='Sales of each year',text_auto=True)

12.Orders in months of year 2022

In [74]:
sales_2022=df[df['Order Date'].dt.year == 2022]
Sa22=sales_2022.groupby(sales_2022['Order Date'].dt.month)['Total price'].sum().reset_index()
# We need to create a new col.named Month 
Sa22['Month']=pd.to_datetime(Sa22['Order Date'],format='%m').dt.month_name()

px.line(Sa22,x='Month',y='Total price',title='Sales of months of year 2022',labels=True,markers=True,)

13.Top selling day in 2022

In [ ]:
sales_2022 = df[df["Order Date"].dt.year == 2022]

best_day =sales_2022.groupby("Order Date", as_index=False)["Total price"].sum().sort_values("Total price", ascending=False).reset_index()
best_day.head(1)

   index Order Date  Total price
0    149 2022-05-30        899.0

14.Top selling day in 2023

In [ ]:
sales_2023 = df[df["Order Date"].dt.year == 2023]

best_day =sales_2023.groupby("Order Date", as_index=False)["Total price"].sum().sort_values("Total price", ascending=False).reset_index()
best_day.head(1)

   index Order Date  Total price
0    328 2023-11-25        999.5

                        Finally we need to save this cleaned data to use it in streamlit

In [ ]:
df.to_csv("restaurant_sales_cleaned.csv", index=False)